### ISSUE TITLE
Paystack Plugin does not display on Jeema Buy sms page

### ISSUE THREAD

**Issue by maillawale** [JibiBanks/paystack#1]
![image](https://user-images.githubusercontent.com/8961021/27344311-c4af5498-55dd-11e7-99c3-1894ba2cc7c9.png)

![image](https://user-images.githubusercontent.com/8961021/27344329-d5bada6e-55dd-11e7-820c-c6a41393973b.png)

![image](https://user-images.githubusercontent.com/8961021/27344354-eb4f1c78-55dd-11e7-9441-7ebdb58cd834.png)

Kindly check, paystack jeema payment plugin does not display after enabling it. Check the attached files for details

Joomla version: Joomla! 3.6.2
Jeema Version: Version: 5.2.0

**Comment by Daydah** [comment]
![image](https://user-images.githubusercontent.com/8342864/27350677-e7fdbc2c-55f2-11e7-8290-2c8b5b4c58bd.png)
Hi!  Its working here.
Joomla version: Joomla! 3.6.5, Jeema version: 5.2.0
Could you enable debugging so we can see the issue?

**Comment by Daydah** [comment]
Hi again. Did you add it under **Payment Currencies**, inside the currency you are using, under **supported plugins**?
If its not under supported plugins in there, it wont show o. Let me know please

**Comment by maillawale** [comment]
Thanks Deydah,

It was not added to payment currencies before, added now and working fine
